// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFeedContent() {
  return window['go']['main']['App']['GetFeedContent']();
}

export function GetFeedList() {
  return window['go']['main']['App']['GetFeedList']();
}
