// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRssContent() {
  return window['go']['main']['App']['GetRssContent']();
}

export function GetRssList() {
  return window['go']['main']['App']['GetRssList']();
}
