// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetRssContent():Promise<Array<backend.RssContentInfo>>;

export function GetRssList():Promise<Array<backend.RssInfo>>;
